#ifndef SDPOTESTMETHODCONVERTERS_H
#define SDPOTESTMETHODCONVERTERS_H

#include "ioCompareFilesConverter.h"
#include "ioCountFilesConverter.h"
#include "ioCPUUsageConverter.h"
#include "ioDHCPConverter.h"
#include "ioDICOMConverter.h"
#include "ioDNSTestConverter.h"
#include "ioDominantProcessConverter.h"
#include "ioDriveSpaceConverter.h"
#include "ioExternalPrgConverter.h"
#include "ioFileContentsConverter.h"
#include "ioFileExistsConverter.h"
#include "ioFolderSizeConverter.h"
#include "ioHTTPConverter.h"
#include "ioIMAPTestConverter.h"
#include "ioInterbaseConverter.h"
#include "ioLDAPTestConverter.h"
#include "ioMailRelayConverter.h"
#include "ioMsSqlConverter.h"
#include "ioMySqlConverter.h"
#include "ioNtEventLogConverter.h"
#include "ioNtpTestConverter.h"
#include "ioODBCConverter.h"
#include "ioOracleConverter.h"
#include "ioPerformanceCounterConverter.h"
#include "ioPingConverter.h"
#include "ioPostgreSqlConverter.h"
#include "ioShellScriptConverter.h"
#include "ioSnmpGetConverter.h"
#include "ioSybaseConverter.h"

#endif // SDPOTESTMETHODCONVERTERS_H
