#ifndef SDPOTESTACTIONS_H
#define SDPOTESTACTIONS_H

#include "tChangeTestIntervalAction.h"
#include "tDialupToTheNetworkAction.h"
#include "tDisconnectDialupConnectionAction.h"
#include "tExecuteExternalProgramAction.h"
#include "tGenerateReportsAction.h"
#include "tHttpRequestAction.h"
#include "tLogEventAction.h"
#include "tPlaySoundAction.h"
#include "tRebootLocalMachineAction.h"
#include "tRebootRemoteSystemAction.h"
#include "tRecordSdpoLogAction.h"
#include "tRepeatTestAction.h"
#include "tRestartServiceAction.h"
#include "tRunHmsScriptAction.h"
#include "tSendDataToTcpUdpPortAction.h"
#include "tSendEmailSmtpAction.h"
#include "tSendMessageToBeeperAction.h"
#include "tSendMessageToIcqAction.h"
#include "tSendMessageToJabberAction.h"
#include "tSendMessageToPagerSnppAction.h"
#include "tSendMessageToPagerTapAction.h"
#include "tSendSmsGsmModemAction.h"
#include "tSendSmsSmppAction.h"
#include "tSnmpSetAction.h"
#include "tSnmpTrapAction.h"
#include "tSqlQueryAction.h"
#include "tStartServiceAction.h"
#include "tStopServiceAction.h"
#include "tSyslogAction.h"
#include "tWinPopupAction.h"

#endif // SDPOTESTACTIONS_H
