QT += sql

INCLUDEPATH += $$PWD
DEPENDPATH += $$PWD

HEADERS += \
    $$PWD/qOptionsForm.h \
    $$PWD/qHostMonDlg.h \
    $$PWD/qMethodSelectDlg.h \
    $$PWD/qLinksList.h \
    $$PWD/qActionProfiles.h \
    $$PWD/qActionProfilesAddMenu.h \
    $$PWD/qActionPropertiesDialog.h \
    $$PWD/hIOShellScripts.h \
    $$PWD/qShellMng.h \
    $$PWD/qMacroEditorDlg.h \
    $$PWD/qGlobalUserVariables.h \
    $$PWD/qConnectionManagerDlg.h \
    $$PWD/qUserPreferencesDlg.h \
    $$PWD/qOperatorsDlg.h \
    $$PWD/qLoginAsDlg.h \
    $$PWD/qMacroEditorScriptRunnerDlg.h \
    $$PWD/qActionPopupEvent.h \
    $$PWD/qMailProfilesDlg.h \
    $$PWD/qReportProfilesDlg.h \
    $$PWD/qPalettesWin.h \
    $$PWD/qPatternsDlg.h \
    $$PWD/action/qShowPopupWindowWidget.h \
    $$PWD/action/qPlaySoundWidget.h \
    $$PWD/action/qSendMessageToPagerTapWidget.h \
    $$PWD/action/qSendMessageToPagerSnppWidget.h \
    $$PWD/action/qSendMessageToBeeperWidget.h \
    $$PWD/action/qSendSmsGsmModemWidget.h \
    $$PWD/action/qSendSmsSmppWidget.h \
    $$PWD/action/qSendEmailSmtpWidget.h \
    $$PWD/action/qSendMessageToIcqWidget.h \
    $$PWD/action/qSendMessageToJabberWidget.h \
    $$PWD/action/qRecordSdpoLogWidget.h \
    $$PWD/action/qGenerateReportsWidget.h \
    $$PWD/action/qStopServiceWidget.h \
    $$PWD/action/qStartServiceWidget.h \
    $$PWD/action/qRestartServiceWidget.h \
    $$PWD/action/qRebootRemoteSystemWidget.h \
    $$PWD/action/qRebootLocalMachineWidget.h \
    $$PWD/action/qDialupToTheNetworkWidget.h \
    $$PWD/action/qDisconnectDialupConnectionWidget.h \
    $$PWD/action/qExecuteExternalProgramWidget.h \
    $$PWD/action/qLogEventWidget.h \
    $$PWD/action/qSqlQueryWidget.h \
    $$PWD/action/qHttpRequestWidget.h \
    $$PWD/action/qSendDataToTcpUdpPortWidget.h \
    $$PWD/action/qSyslogWidget.h \
    $$PWD/action/qSnmpSetWidget.h \
    $$PWD/action/qSnmpTrapWidgets.h \
    $$PWD/action/qRepeatTestWidget.h \
    $$PWD/action/qChangeTestIntervalWidget.h \
    $$PWD/action/qRunHmsScriptWidget.h \
    $$PWD/method/qTestWidget.h \
    $$PWD/method/qPingWidget.h \
    $$PWD/method/qTcpWidget.h \
    $$PWD/method/qUrlWidget.h \
    $$PWD/method/qUrlTestPropertiesDlg.h \
    $$PWD/method/qDriveSpaceWidget.h \
    $$PWD/method/qFileSizeWidget.h \
    $$PWD/method/qFileExistsWidget.h \
    $$PWD/method/qExternalPrgWidget.h \
    $$PWD/method/qSshWidget.h \
    $$PWD/method/qFileContentsWidget.h \
    $$PWD/method/qOracleWidget.h \
    $$PWD/method/qUncWidget.h \
    $$PWD/method/qInterbaseWidget.h \
    $$PWD/method/qMsSqlWidget.h \
    $$PWD/method/qMySqlWidget.h \
    $$PWD/method/qPostgreSqlWidget.h \
    $$PWD/method/qSybaseWidget.h \
    $$PWD/method/qProcessWidget.h \
    $$PWD/method/qServiceWidget.h \
    $$PWD/method/qServiceToMonitorDlg.h \
    $$PWD/method/qSnmpGetWidget.h \
    $$PWD/method/qNtEventLogWidget.h \
    $$PWD/method/qDriveSpaceSimpleWidget.h \
    $$PWD/method/qCpuUsageWidget.h \
    $$PWD/method/qCompareFilesWidget.h \
    $$PWD/method/qOdbcQueryWidget.h \
    $$PWD/method/qSmtpTestWidget.h \
    $$PWD/method/qOdbcQueryDlg.h \
    $$PWD/method/qPop3TestWidget.h \
    $$PWD/method/qImapTestWidget.h \
    $$PWD/method/qDnsTestWidget.h \
    $$PWD/method/qLdapTestWidget.h \
    $$PWD/method/qTraceTestWidget.h \
    $$PWD/method/qCountFilesWidget.h \
    $$PWD/method/qRasTestWidget.h \
    $$PWD/method/qPerformanceCounterWidget.h \
    $$PWD/method/qShellScriptWidget.h \
    $$PWD/method/qActiveScriptWidget.h \
    $$PWD/method/qUdpTestWidget.h \
    $$PWD/method/qNtpTestWidget.h \
    $$PWD/method/qRadiusWidget.h \
    $$PWD/method/qHttpWidget.h \
    $$PWD/method/qHttpTestPropertiesDlg.h \
    $$PWD/method/qHttpProxiesListDlg.h \
    $$PWD/method/qTextLogWidget.h \
    $$PWD/method/qTextLogPropertiesDlg.h \
    $$PWD/method/qTemperatureMonitorWidget.h \
    $$PWD/method/qTrafficMonitorWidget.h \
    $$PWD/method/qTrafficNetworkInterfaceDlg.h \
    $$PWD/method/qTrafficSnmpCredentialsDlg.h \
    $$PWD/method/qSnmpTrapWidget.h \
    $$PWD/method/qSnmpTrapFilterDlg.h \
    $$PWD/method/qWmiWidget.h \
    $$PWD/method/qMailRelayTestPropertiesDlg.h \
    $$PWD/method/qMailRelayWidget.h \
    $$PWD/method/qDicomWidget.h \
    $$PWD/method/qDominantProcessWidget.h \
    $$PWD/method/qDhcpWidget.h \
    $$PWD/method/qSdpoMonitorWidget.h \
    $$PWD/method/qMibBrowser.h \
    $$PWD/action/qActionWidget.h \
    $$PWD/options/qOptionsWidget.h \
    $$PWD/options/qPreferencesWidget.h \
    $$PWD/options/qBehaviorWidget.h \
    $$PWD/options/qStartupOptionsWidget.h \
    $$PWD/options/qServiceOptionsWidget.h \
    $$PWD/options/qAccessMethodOptionsWidget.h \
    $$PWD/options/qProxyOptionsWidget.h \
    $$PWD/options/qPrimaryLogOptionsWidget.h \
    $$PWD/options/qBackupLogOptionsWidget.h \
    $$PWD/options/qSystemLogOptionsWidget.h \
    $$PWD/options/qLogProcessingOptionsWidget.h \
    $$PWD/options/qHtmlColorsOptionsWidget.h \
    $$PWD/options/qViewersOptionsWidget.h \
    $$PWD/options/qReportsOptionsWidget.h \
    $$PWD/options/qMsgWindowOptionsWidget.h \
    $$PWD/options/qMailerSettingsWidget.h \
    $$PWD/options/qPagersOptionsWidget.h \
    $$PWD/options/qIcqOptionsWidget.h \
    $$PWD/options/qJabberOptionsWidget.h \
    $$PWD/options/qSmsGsmOptionsWidget.h \
    $$PWD/options/qSmsSmppOptionsWidget.h \
    $$PWD/options/qPingTraceOptionsWidget.h \
    $$PWD/options/qRciOptionsWidget.h \
    $$PWD/options/qActiveRmaServerOptionsWidget.h \
    $$PWD/options/qSchedulerOptionsWidget.h \
    $$PWD/options/qMiscellaneousOptionsWidget.h \
    $$PWD/testedit/qAlertsEditWidget.h \
    $$PWD/testedit/qLogReportsEditWidget.h \
    $$PWD/testedit/qMasterTestsEditWidget.h \
    $$PWD/testedit/qExpressionTestsEditWidget.h \
    $$PWD/testedit/qAddMasterTestDlg.h \
    $$PWD/viewmodel/mShellScript.h \
    $$PWD/viewmodel/mTestListModel.h \
    $$PWD/viewmodel/mTestsTreeModel.h \
    $$PWD/viewmodel/mFoldersAndViewsModel.h \
    $$PWD/viewmodel/mTestListSortingModel.h \
    $$PWD/viewmodel/mPalettesTreeModel.h \
    ../view/properties/qColumnsPropertiesWidget.h \
    ../view/qDynamicViewReportsWidget.h \
    ../view/properties/qColorsPropertiesWidget.h \
    ../view/properties/qCommentPropertiesWidget.h \
    ../view/properties/qViewCriteriaPropertiesWidget.h \
    ../view/qDynamicViewPropertiesDlg.h \
    ../view/qFolderPropertiesDlg.h \
    ../view/qFolderPropertiesStatisticWidget.h \
    ../view/properties/qRegionalPropertiesWidget.h \
    ../view/properties/qSpecialsPropertiesWidget.h \
    ../view/qUserPreferencesCopyDlg.h \
    ../view/qCommonViewPropertiesDlg.h

SOURCES += \
    $$PWD/qOptionsForm.cpp \
    $$PWD/qHostMonDlg.cpp \
    $$PWD/qMethodSelectDlg.cpp \
    $$PWD/qLinksList.cpp \
    $$PWD/qActionProfiles.cpp \
    $$PWD/qActionProfilesAddMenu.cpp \
    $$PWD/qActionPropertiesDialog.cpp \
    $$PWD/hIOShellScripts.cpp \
    $$PWD/qShellMng.cpp \
    $$PWD/qMacroEditorDlg.cpp \
    $$PWD/qGlobalUserVariables.cpp \
    $$PWD/qConnectionManagerDlg.cpp \
    $$PWD/qUserPreferencesDlg.cpp \
    $$PWD/qOperatorsDlg.cpp \
    $$PWD/qLoginAsDlg.cpp \
    $$PWD/qMacroEditorScriptRunnerDlg.cpp \
    $$PWD/qActionPopupEvent.cpp \
    $$PWD/qMailProfilesDlg.cpp \
    $$PWD/qReportProfilesDlg.cpp \
    $$PWD/qPalettesWin.cpp \
    $$PWD/qPatternsDlg.cpp \
    $$PWD/action/qActionWidget.cpp \
    $$PWD/action/qShowPopupWindowWidget.cpp \
    $$PWD/action/qPlaySoundWidget.cpp \
    $$PWD/action/qSendMessageToPagerTapWidget.cpp \
    $$PWD/action/qSendMessageToPagerSnppWidget.cpp \
    $$PWD/action/qSendMessageToBeeperWidget.cpp \
    $$PWD/action/qSendSmsGsmModemWidget.cpp \
    $$PWD/action/qSendSmsSmppWidget.cpp \
    $$PWD/action/qSendEmailSmtpWidget.cpp \
    $$PWD/action/qSendMessageToIcqWidget.cpp \
    $$PWD/action/qSendMessageToJabberWidget.cpp \
    $$PWD/action/qRecordSdpoLogWidget.cpp \
    $$PWD/action/qGenerateReportsWidget.cpp \
    $$PWD/action/qStopServiceWidget.cpp \
    $$PWD/action/qStartServiceWidget.cpp \
    $$PWD/action/qRestartServiceWidget.cpp \
    $$PWD/action/qRebootRemoteSystemWidget.cpp \
    $$PWD/action/qRebootLocalMachineWidget.cpp \
    $$PWD/action/qDialupToTheNetworkWidget.cpp \
    $$PWD/action/qDisconnectDialupConnectionWidget.cpp \
    $$PWD/action/qExecuteExternalProgramWidget.cpp \
    $$PWD/action/qLogEventWidget.cpp \
    $$PWD/action/qSqlQueryWidget.cpp \
    $$PWD/action/qHttpRequestWidget.cpp \
    $$PWD/action/qSendDataToTcpUdpPortWidget.cpp \
    $$PWD/action/qSyslogWidget.cpp \
    $$PWD/action/qSnmpSetWidget.cpp \
    $$PWD/action/qSnmpTrapWidgets.cpp \
    $$PWD/action/qRepeatTestWidget.cpp \
    $$PWD/action/qChangeTestIntervalWidget.cpp \
    $$PWD/action/qRunHmsScriptWidget.cpp \
    $$PWD/method/qTestWidget.cpp \
    $$PWD/method/qPingWidget.cpp \
    $$PWD/method/qTcpWidget.cpp \
    $$PWD/method/qUrlWidget.cpp \
    $$PWD/method/qUrlTestPropertiesDlg.cpp \
    $$PWD/method/qDriveSpaceWidget.cpp \
    $$PWD/method/qFileSizeWidget.cpp \
    $$PWD/method/qFileExistsWidget.cpp \
    $$PWD/method/qExternalPrgWidget.cpp \
    $$PWD/method/qSshWidget.cpp \
    $$PWD/method/qFileContentsWidget.cpp \
    $$PWD/method/qOracleWidget.cpp \
    $$PWD/method/qUncWidget.cpp \
    $$PWD/method/qInterbaseWidget.cpp \
    $$PWD/method/qMsSqlWidget.cpp \
    $$PWD/method/qMySqlWidget.cpp \
    $$PWD/method/qPostgreSqlWidget.cpp \
    $$PWD/method/qSybaseWidget.cpp \
    $$PWD/method/qProcessWidget.cpp \
    $$PWD/method/qServiceWidget.cpp \
    $$PWD/method/qServiceToMonitorDlg.cpp \
    $$PWD/method/qSnmpGetWidget.cpp \
    $$PWD/method/qNtEventLogWidget.cpp \
    $$PWD/method/qDriveSpaceSimpleWidget.cpp \
    $$PWD/method/qCpuUsageWidget.cpp \
    $$PWD/method/qCompareFilesWidget.cpp \
    $$PWD/method/qOdbcQueryWidget.cpp \
    $$PWD/method/qSmtpTestWidget.cpp \
    $$PWD/method/qOdbcQueryDlg.cpp \
    $$PWD/method/qPop3TestWidget.cpp \
    $$PWD/method/qImapTestWidget.cpp \
    $$PWD/method/qDnsTestWidget.cpp \
    $$PWD/method/qLdapTestWidget.cpp \
    $$PWD/method/qTraceTestWidget.cpp \
    $$PWD/method/qCountFilesWidget.cpp \
    $$PWD/method/qRasTestWidget.cpp \
    $$PWD/method/qPerformanceCounterWidget.cpp \
    $$PWD/method/qShellScriptWidget.cpp \
    $$PWD/method/qActiveScriptWidget.cpp \
    $$PWD/method/qUdpTestWidget.cpp \
    $$PWD/method/qNtpTestWidget.cpp \
    $$PWD/method/qRadiusWidget.cpp \
    $$PWD/method/qHttpWidget.cpp \
    $$PWD/method/qHttpTestPropertiesDlg.cpp \
    $$PWD/method/qHttpProxiesListDlg.cpp \
    $$PWD/method/qTextLogWidget.cpp \
    $$PWD/method/qTextLogPropertiesDlg.cpp \
    $$PWD/method/qTemperatureMonitorWidget.cpp \
    $$PWD/method/qTrafficMonitorWidget.cpp \
    $$PWD/method/qTrafficNetworkInterfaceDlg.cpp \
    $$PWD/method/qTrafficSnmpCredentialsDlg.cpp \
    $$PWD/method/qSnmpTrapWidget.cpp \
    $$PWD/method/qSnmpTrapFilterDlg.cpp \
    $$PWD/method/qWmiWidget.cpp \
    $$PWD/method/qMailRelayTestPropertiesDlg.cpp \
    $$PWD/method/qMailRelayWidget.cpp \
    $$PWD/method/qDicomWidget.cpp \
    $$PWD/method/qDominantProcessWidget.cpp \
    $$PWD/method/qDhcpWidget.cpp \
    $$PWD/method/qSdpoMonitorWidget.cpp \
    $$PWD/method/qMibBrowser.cpp \
    $$PWD/options/qOptionsWidget.cpp \
    $$PWD/options/qPreferencesWidget.cpp \
    $$PWD/options/qBehaviorWidget.cpp \
    $$PWD/options/qStartupOptionsWidget.cpp \
    $$PWD/options/qServiceOptionsWidget.cpp \
    $$PWD/options/qAccessMethodOptionsWidget.cpp \
    $$PWD/options/qProxyOptionsWidget.cpp \
    $$PWD/options/qPrimaryLogOptionsWidget.cpp \
    $$PWD/options/qBackupLogOptionsWidget.cpp \
    $$PWD/options/qSystemLogOptionsWidget.cpp \
    $$PWD/options/qLogProcessingOptionsWidget.cpp \
    $$PWD/options/qHtmlColorsOptionsWidget.cpp \
    $$PWD/options/qViewersOptionsWidget.cpp \
    $$PWD/options/qReportsOptionsWidget.cpp \
    $$PWD/options/qMsgWindowOptionsWidget.cpp \
    $$PWD/options/qMailerSettingsWidget.cpp \
    $$PWD/options/qPagersOptionsWidget.cpp \
    $$PWD/options/qIcqOptionsWidget.cpp \
    $$PWD/options/qJabberOptionsWidget.cpp \
    $$PWD/options/qSmsGsmOptionsWidget.cpp \
    $$PWD/options/qSmsSmppOptionsWidget.cpp \
    $$PWD/options/qPingTraceOptionsWidget.cpp \
    $$PWD/options/qRciOptionsWidget.cpp \
    $$PWD/options/qActiveRmaServerOptionsWidget.cpp \
    $$PWD/options/qSchedulerOptionsWidget.cpp \
    $$PWD/options/qMiscellaneousOptionsWidget.cpp \
    $$PWD/testedit/qAlertsEditWidget.cpp \
    $$PWD/testedit/qLogReportsEditWidget.cpp \
    $$PWD/testedit/qMasterTestsEditWidget.cpp \
    $$PWD/testedit/qExpressionTestsEditWidget.cpp \
    $$PWD/testedit/qAddMasterTestDlg.cpp \
    $$PWD/viewmodel/mShellScript.cpp \
    $$PWD/viewmodel/mTestListModel.cpp \
    $$PWD/viewmodel/mTestsTreeModel.cpp \
    $$PWD/viewmodel/mFoldersAndViewsModel.cpp \
    $$PWD/viewmodel/mTestListSortingModel.cpp \
    $$PWD/viewmodel/mPalettesTreeModel.cpp \
    ../view/properties/qColumnsPropertiesWidget.cpp \
    ../view/qDynamicViewReportsWidget.cpp \
    ../view/properties/qColorsPropertiesWidget.cpp \
    ../view/properties/qCommentPropertiesWidget.cpp \
    ../view/properties/qViewCriteriaPropertiesWidget.cpp \
    ../view/qDynamicViewPropertiesDlg.cpp \
    ../view/qFolderPropertiesDlg.cpp \
    ../view/qFolderPropertiesStatisticWidget.cpp \
    ../view/properties/qRegionalPropertiesWidget.cpp \
    ../view/properties/qSpecialsPropertiesWidget.cpp \
    ../view/qUserPreferencesCopyDlg.cpp \
    ../view/qCommonViewPropertiesDlg.cpp

FORMS    += \
    $$PWD/qOptionsForm.ui \
    $$PWD/qHostMonDlg.ui \
    $$PWD/qMethodSelectDlg.ui \
    $$PWD/qLinksList.ui \
    $$PWD/qActionProfiles.ui \
    $$PWD/qActionProfilesAddMenu.ui \
    $$PWD/qActionPropertiesDialog.ui \
    $$PWD/qShellMng.ui \
    $$PWD/qMacroEditorDlg.ui \
    $$PWD/qGlobalUserVariables.ui \
    $$PWD/qConnectionManagerDlg.ui \
    $$PWD/qUserPreferencesDlg.ui \
    $$PWD/qOperatorsDlg.ui \
    $$PWD/qLoginAsDlg.ui \
    $$PWD/qMacroEditorScriptRunnerDlg.ui \
    $$PWD/qActionPopupEvent.ui \
    $$PWD/qMailProfilesDlg.ui \
    $$PWD/qReportProfilesDlg.ui \
    $$PWD/qPalettesWin.ui \
    $$PWD/qPatternsDlg.ui \
    $$PWD/action/qShowPopupWindowWidget.ui \
    $$PWD/action/qPlaySoundWidget.ui \
    $$PWD/action/qSendMessageToPagerTapWidget.ui \
    $$PWD/action/qSendMessageToPagerSnppWidget.ui \
    $$PWD/action/qSendMessageToBeeperWidget.ui \
    $$PWD/action/qSendSmsGsmModemWidget.ui \
    $$PWD/action/qSendSmsSmppWidget.ui \
    $$PWD/action/qSendEmailSmtpWidget.ui \
    $$PWD/action/qSendMessageToIcqWidget.ui \
    $$PWD/action/qSendMessageToJabberWidget.ui \
    $$PWD/action/qRecordSdpoLogWidget.ui \
    $$PWD/action/qGenerateReportsWidget.ui \
    $$PWD/action/qStopServiceWidget.ui \
    $$PWD/action/qStartServiceWidget.ui \
    $$PWD/action/qRestartServiceWidget.ui \
    $$PWD/action/qRebootRemoteSystemWidget.ui \
    $$PWD/action/qRebootLocalMachineWidget.ui \
    $$PWD/action/qDialupToTheNetworkWidget.ui \
    $$PWD/action/qDisconnectDialupConnectionWidget.ui \
    $$PWD/action/qExecuteExternalProgramWidget.ui \
    $$PWD/action/qLogEventWidget.ui \
    $$PWD/action/qSqlQueryWidget.ui \
    $$PWD/action/qHttpRequestWidget.ui \
    $$PWD/action/qSendDataToTcpUdpPortWidget.ui \
    $$PWD/action/qSyslogWidget.ui \
    $$PWD/action/qSnmpSetWidget.ui \
    $$PWD/action/qSnmpTrapWidgets.ui \
    $$PWD/action/qRepeatTestWidget.ui \
    $$PWD/action/qChangeTestIntervalWidget.ui \
    $$PWD/action/qRunHmsScriptWidget.ui \
    $$PWD/method/qPingWidget.ui \
    $$PWD/method/qTcpWidget.ui \
    $$PWD/method/qUrlWidget.ui \
    $$PWD/method/qUrlTestPropertiesDlg.ui\
    $$PWD/method/qDriveSpaceWidget.ui \
    $$PWD/method/qFileSizeWidget.ui \
    $$PWD/method/qFileExistsWidget.ui \
    $$PWD/method/qExternalPrgWidget.ui \
    $$PWD/method/qSshWidget.ui \
    $$PWD/method/qFileContentsWidget.ui \
    $$PWD/method/qOracleWidget.ui \
    $$PWD/method/qUncWidget.ui \
    $$PWD/method/qInterbaseWidget.ui \
    $$PWD/method/qMsSqlWidget.ui \
    $$PWD/method/qMySqlWidget.ui \
    $$PWD/method/qPostgreSqlWidget.ui \
    $$PWD/method/qSybaseWidget.ui \
    $$PWD/method/qProcessWidget.ui \
    $$PWD/method/qServiceWidget.ui \
    $$PWD/method/qServiceToMonitorDlg.ui \
    $$PWD/method/qSnmpGetWidget.ui \
    $$PWD/method/qNtEventLogWidget.ui \
    $$PWD/method/qDriveSpaceSimpleWidget.ui \
    $$PWD/method/qCpuUsageWidget.ui \
    $$PWD/method/qCompareFilesWidget.ui \
    $$PWD/method/qOdbcQueryWidget.ui \
    $$PWD/method/qSmtpTestWidget.ui \
    $$PWD/method/qOdbcQueryDlg.ui \
    $$PWD/method/qPop3TestWidget.ui \
    $$PWD/method/qImapTestWidget.ui \
    $$PWD/method/qDnsTestWidget.ui \
    $$PWD/method/qLdapTestWidget.ui \
    $$PWD/method/qTraceTestWidget.ui \
    $$PWD/method/qCountFilesWidget.ui \
    $$PWD/method/qRasTestWidget.ui \
    $$PWD/method/qPerformanceCounterWidget.ui \
    $$PWD/method/qShellScriptWidget.ui \
    $$PWD/method/qActiveScriptWidget.ui \
    $$PWD/method/qUdpTestWidget.ui \
    $$PWD/method/qNtpTestWidget.ui \
    $$PWD/method/qRadiusWidget.ui \
    $$PWD/method/qHttpWidget.ui \
    $$PWD/method/qHttpTestPropertiesDlg.ui \
    $$PWD/method/qHttpProxiesListDlg.ui \
    $$PWD/method/qTextLogWidget.ui \
    $$PWD/method/qTextLogPropertiesDlg.ui \
    $$PWD/method/qTemperatureMonitorWidget.ui \
    $$PWD/method/qTrafficMonitorWidget.ui \
    $$PWD/method/qTrafficNetworkInterfaceDlg.ui \
    $$PWD/method/qTrafficSnmpCredentialsDlg.ui \
    $$PWD/method/qSnmpTrapWidget.ui \
    $$PWD/method/qSnmpTrapFilterDlg.ui \
    $$PWD/method/qWmiWidget.ui \
    $$PWD/method/qMailRelayTestPropertiesDlg.ui \
    $$PWD/method/qMailRelayWidget.ui \
    $$PWD/method/qDicomWidget.ui \
    $$PWD/method/qDominantProcessWidget.ui \
    $$PWD/method/qDhcpWidget.ui \
    $$PWD/method/qSdpoMonitorWidget.ui \
    $$PWD/method/qMibBrowser.ui \
    $$PWD/options/qPreferencesWidget.ui \
    $$PWD/options/qBehaviorWidget.ui \
    $$PWD/options/qStartupOptionsWidget.ui \
    $$PWD/options/qServiceOptionsWidget.ui \
    $$PWD/options/qAccessMethodOptionsWidget.ui \
    $$PWD/options/qProxyOptionsWidget.ui \
    $$PWD/options/qPrimaryLogOptionsWidget.ui \
    $$PWD/options/qBackupLogOptionsWidget.ui \
    $$PWD/options/qSystemLogOptionsWidget.ui \
    $$PWD/options/qLogProcessingOptionsWidget.ui \
    $$PWD/options/qHtmlColorsOptionsWidget.ui \
    $$PWD/options/qViewersOptionsWidget.ui \
    $$PWD/options/qReportsOptionsWidget.ui \
    $$PWD/options/qMsgWindowOptionsWidget.ui \
    $$PWD/options/qMailerSettingsWidget.ui \
    $$PWD/options/qPagersOptionsWidget.ui \
    $$PWD/options/qIcqOptionsWidget.ui \
    $$PWD/options/qJabberOptionsWidget.ui \
    $$PWD/options/qSmsGsmOptionsWidget.ui \
    $$PWD/options/qSmsSmppOptionsWidget.ui \
    $$PWD/options/qPingTraceOptionsWidget.ui \
    $$PWD/options/qRciOptionsWidget.ui \
    $$PWD/options/qActiveRmaServerOptionsWidget.ui \
    $$PWD/options/qSchedulerOptionsWidget.ui \
    $$PWD/options/qMiscellaneousOptionsWidget.ui \
    $$PWD/testedit/qAlertsEditWidget.ui \
    $$PWD/testedit/qLogReportsEditWidget.ui \
    $$PWD/testedit/qMasterTestsEditWidget.ui \
    $$PWD/testedit/qExpressionTestsEditWidget.ui \
    $$PWD/testedit/qAddMasterTestDlg.ui \
    ../view/properties/qColumnsPropertiesWidget.ui \
    ../view/qDynamicViewReportsWidget.ui \
    ../view/properties/qColorsPropertiesWidget.ui \
    ../view/properties/qCommentPropertiesWidget.ui \
    ../view/properties/qViewCriteriaPropertiesWidget.ui \
    ../view/qDynamicViewPropertiesDlg.ui \
    ../view/qFolderPropertiesDlg.ui \
    ../view/qFolderPropertiesStatisticWidget.ui \
    ../view/properties/qRegionalPropertiesWidget.ui \
    ../view/properties/qSpecialsPropertiesWidget.ui \
    ../view/qUserPreferencesCopyDlg.ui \
    ../view/qCommonViewPropertiesDlg.ui



