#ifndef SDPOTESTMETHODS_H
#define SDPOTESTMETHODS_H

#include "tActiveScript.h"
#include "tCompareFiles.h"
#include "tCountFiles.h"
#include "tCpuUsage.h"
#include "tDhcp.h"
#include "tDicom.h"
#include "tDnsTest.h"
#include "tDominantProcess.h"
#include "tDriveSpace.h"
#include "tExternalPrg.h"
#include "tFileContents.h"
#include "tFileExists.h"
#include "tFolderSize.h"
#include "tHttp.h"
#include "tImapTest.h"
#include "tInterbase.h"
#include "tLdapTest.h"
#include "tMailRelay.h"
#include "tMsSql.h"
#include "tMySql.h"
#include "tNtEventLog.h"
#include "tNtpTest.h"
#include "tOdbcQuery.h"
#include "tOracle.h"
#include "tPerformanceCounter.h"
#include "tPing.h"
#include "tPostgreSql.h"
#include "tShellScript.h"
#include "tSnmpGet.h"
#include "tSybase.h"
#include "tWmi.h"

#endif // SDPOTESTMETHODS_H
